// Generates public/_headers (security + caching) and public/robots.txt from build env.
//   PUBLIC_NOINDEX=true      -> staging: noindex + disallow all
//   PUBLIC_GA4_ID / PUBLIC_META_PIXEL_ID -> widen CSP only for configured vendors
import { existsSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const modeAt = process.argv.indexOf('--mode');
const mode = modeAt > -1 ? process.argv[modeAt + 1] : 'production';
// Same precedence as Astro: shell env > .env.<mode>.local > .env.<mode> > .env.local > .env (first load wins).
for (const f of [`.env.${mode}.local`, `.env.${mode}`, '.env.local', '.env']) {
  const p = join(ROOT, f);
  if (existsSync(p)) process.loadEnvFile(p);
}
const env = process.env;
const noindex = env.PUBLIC_NOINDEX === 'true';
const ga = !!env.PUBLIC_GA4_ID;
const meta = !!env.PUBLIC_META_PIXEL_ID;
const SITE = 'https://kalolipointparadisehawaii.com';

const src = (...xs) => xs.filter(Boolean).join(' ');
const csp = [
  "default-src 'self'",
  `script-src ${src("'self'", 'https://challenges.cloudflare.com', ga && 'https://www.googletagmanager.com', meta && 'https://connect.facebook.net')}`,
  "style-src 'self' 'unsafe-inline'",
  `img-src ${src("'self'", 'data:', 'blob:', ga && 'https://*.google-analytics.com https://*.googletagmanager.com', meta && 'https://www.facebook.com')}`,
  "font-src 'self'",
  "media-src 'self' blob:",
  `connect-src ${src("'self'", 'https://challenges.cloudflare.com', ga && 'https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com', meta && 'https://www.facebook.com https://connect.facebook.net')}`,
  'frame-src https://challenges.cloudflare.com',
  "worker-src 'self' blob:",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
].join('; ');

const security = [
  `  Content-Security-Policy: ${csp}`,
  '  Strict-Transport-Security: max-age=31536000; includeSubDomains',
  '  X-Content-Type-Options: nosniff',
  '  X-Frame-Options: DENY',
  '  Referrer-Policy: strict-origin-when-cross-origin',
  '  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), browsing-topics=()',
  '  Cross-Origin-Opener-Policy: same-origin',
  noindex ? '  X-Robots-Tag: noindex, nofollow' : '',
].filter(Boolean);

const headers = `# Generated by tools/gen-headers.mjs — do not edit by hand.
/*
${security.join('\n')}

/_astro/*
  Cache-Control: public, max-age=31536000, immutable

/media/film/*
  Cache-Control: public, max-age=2592000

/media/film/*.m3u8
  Cache-Control: public, max-age=3600
  Content-Type: application/vnd.apple.mpegurl

/media/film/*.m4s
  Content-Type: video/iso.segment

/fonts/*
  Cache-Control: public, max-age=31536000, immutable
`;

const robots = noindex
  ? 'User-agent: *\nDisallow: /\n'
  : `User-agent: *\nAllow: /\nDisallow: /api/\n\nSitemap: ${SITE}/sitemap-index.xml\n`;

writeFileSync(join(ROOT, 'public', '_headers'), headers);
writeFileSync(join(ROOT, 'public', 'robots.txt'), robots);
console.log(`headers + robots written (${noindex ? 'staging/noindex' : 'production'}; ga=${ga} meta=${meta})`);
